"""Provider interface independent of HTTP and persistence implementations."""

from typing import Protocol

from dohavocal.domain.artifacts import VocalArtifact
from dohavocal.domain.jobs import AnyVocalJob, CreateVocalJobRequest, JobType
from dohavocal.domain.manifests import ModelManifest


class VocalProvider(Protocol):
    def get_capabilities(self) -> tuple[JobType, ...]: ...

    def create_job(self, request: CreateVocalJobRequest) -> AnyVocalJob: ...

    def get_job_status(self, job_id: str) -> AnyVocalJob: ...

    def cancel_job(self, job_id: str) -> AnyVocalJob: ...

    def retry_job(self, job_id: str) -> AnyVocalJob: ...

    def get_result(self, job_id: str) -> VocalArtifact: ...

    def get_model_manifest(self, model_manifest_id: str) -> ModelManifest: ...

    def health(self) -> bool: ...

    def readiness(self) -> bool: ...
