"""Storage boundaries shared by in-memory and durable runtime adapters."""

from contextlib import AbstractContextManager
from typing import Protocol

from dohavocal.domain.jobs import AnyVocalJob, CreateVocalJobRequest, JobStatus
from dohavocal.domain.payloads import AnyVocalArtifact, PayloadArtifact, PayloadContent


class JobStore(Protocol):
    def resolve_idempotency(
        self, request: CreateVocalJobRequest, fingerprint: str
    ) -> AnyVocalJob | None: ...
    def add(
        self, job: AnyVocalJob, request: CreateVocalJobRequest, fingerprint: str
    ) -> AnyVocalJob | None: ...
    def get(self, job_id: str) -> AnyVocalJob: ...
    def get_request(self, job_id: str) -> CreateVocalJobRequest: ...
    def replace(self, job: AnyVocalJob) -> None: ...
    def replace_if_status(
        self, job: AnyVocalJob, expected_status: JobStatus
    ) -> AnyVocalJob: ...
    def count(self) -> int: ...


class ArtifactStore(Protocol):
    def add(self, artifact: AnyVocalArtifact) -> None: ...
    def get(self, artifact_id: str) -> AnyVocalArtifact: ...
    def count(self) -> int: ...


class PayloadStore(Protocol):
    def add(self, result: PayloadArtifact, content: bytes) -> None: ...
    def verify_result(self, result: PayloadArtifact) -> None: ...
    def acquire(self, result: PayloadArtifact) -> PayloadContent: ...
    def contains_source(self, source_id: str) -> bool: ...
    def count(self) -> int: ...


class RuntimeUnitOfWork(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def checkpoint(self, name: str) -> None: ...
    def readiness(self) -> bool: ...
    def close(self) -> None: ...
